[2024-06-18T17:16:39.382+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:16:39.403+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: database_backup.send_mail manual__2024-06-18T11:31:19.712233+00:00 [queued]>
[2024-06-18T17:16:39.409+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: database_backup.send_mail manual__2024-06-18T11:31:19.712233+00:00 [queued]>
[2024-06-18T17:16:39.409+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:16:39.421+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 11:31:19.712233+00:00
[2024-06-18T17:16:39.424+0545] {standard_task_runner.py:63} INFO - Started process 4386 to run task
[2024-06-18T17:16:39.427+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'database_backup', 'send_mail', 'manual__2024-06-18T11:31:19.712233+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp53l_gsn2']
[2024-06-18T17:16:39.428+0545] {standard_task_runner.py:91} INFO - Job 25: Subtask send_mail
[2024-06-18T17:16:39.465+0545] {task_command.py:426} INFO - Running <TaskInstance: database_backup.send_mail manual__2024-06-18T11:31:19.712233+00:00 [running]> on host PRABAL-10.
[2024-06-18T17:16:39.526+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='database_backup' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:31:19.712233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:31:19.712233+00:00'
[2024-06-18T17:16:39.527+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:16:39.537+0545] {logging_mixin.py:188} WARNING - /home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T17:16:39.537+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T17:16:41.882+0545] {email.py:282} INFO - Sent an alert email to ['susmapant@gmail.com']
[2024-06-18T17:16:44.083+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:16:44.091+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=database_backup, task_id=send_mail, run_id=manual__2024-06-18T11:31:19.712233+00:00, execution_date=20240618T113119, start_date=20240618T113139, end_date=20240618T113144
[2024-06-18T17:16:44.148+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:16:44.175+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:16:44.176+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
