[2024-06-18T14:05:03.330+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:05:03.350+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [queued]>
[2024-06-18T14:05:03.354+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [queued]>
[2024-06-18T14:05:03.354+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:05:03.364+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:10:00+00:00
[2024-06-18T14:05:03.366+0545] {standard_task_runner.py:63} INFO - Started process 20631 to run task
[2024-06-18T14:05:03.371+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:10:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp0yn88899']
[2024-06-18T14:05:03.372+0545] {standard_task_runner.py:91} INFO - Job 9: Subtask backup_task
[2024-06-18T14:05:03.443+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:10:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T14:05:03.501+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T08:10:00+00:00'
[2024-06-18T14:05:03.501+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:05:03.502+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T14:05:03.503+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T14:05:03.507+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T14:05:03.513+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T14:05:03.540+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T14:05:03.550+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T14:05:03.567+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T14:05:03.567+0545] {subprocess.py:93} INFO - Backup Success in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1257.96GB
[2024-06-18T14:05:03.568+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T14:05:03.568+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:05:03.582+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:10:00+00:00, execution_date=20240618T081000, start_date=20240618T082003, end_date=20240618T082003
[2024-06-18T14:05:03.624+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T14:05:03.660+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:05:03.665+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
