[2024-06-18T13:48:48.877+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:48:48.906+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:48:48.912+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:48:48.913+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:48:48.924+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:48:48.926+0545] {standard_task_runner.py:63} INFO - Started process 16046 to run task
[2024-06-18T13:48:48.930+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmpsjd41bxu']
[2024-06-18T13:48:48.931+0545] {standard_task_runner.py:91} INFO - Job 2: Subtask backup_task
[2024-06-18T13:48:48.992+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:48:49.064+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:48:49.065+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:48:49.066+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:48:49.067+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T13:48:49.072+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:48:49.079+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:48:49.110+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:48:49.118+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T13:48:49.137+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T13:48:49.137+0545] {subprocess.py:93} INFO - Backup Success in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1257.95GB
[2024-06-18T13:48:49.137+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T13:48:49.137+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:48:49.150+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080348, end_date=20240618T080349
[2024-06-18T13:48:49.184+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:48:49.221+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:48:49.225+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T13:51:32.985+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:51:33.022+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:51:33.030+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:51:33.030+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:51:33.046+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:51:33.048+0545] {standard_task_runner.py:63} INFO - Started process 16849 to run task
[2024-06-18T13:51:33.053+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmpzw3prykf']
[2024-06-18T13:51:33.053+0545] {standard_task_runner.py:91} INFO - Job 2: Subtask backup_task
[2024-06-18T13:51:33.121+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:51:33.188+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:51:33.189+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:51:33.190+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:51:33.190+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T13:51:33.196+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:51:33.204+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:51:33.231+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:51:33.247+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T13:51:33.278+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T13:51:33.279+0545] {subprocess.py:93} INFO - Backup Success in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1257.95GB
[2024-06-18T13:51:33.279+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T13:51:33.280+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:51:33.308+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080633, end_date=20240618T080633
[2024-06-18T13:51:33.345+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:51:33.385+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:51:33.392+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T13:52:51.414+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:52:51.434+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:52:51.442+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:52:51.442+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:52:51.457+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:52:51.459+0545] {standard_task_runner.py:63} INFO - Started process 17275 to run task
[2024-06-18T13:52:51.463+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmphavqboch']
[2024-06-18T13:52:51.463+0545] {standard_task_runner.py:91} INFO - Job 2: Subtask backup_task
[2024-06-18T13:52:51.517+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:52:51.589+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:52:51.590+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:52:51.591+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:52:51.592+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T13:52:51.597+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:52:51.605+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:52:51.643+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:52:51.652+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T13:52:51.673+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T13:52:51.673+0545] {subprocess.py:93} INFO - Backup Success in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1257.88GB
[2024-06-18T13:52:51.673+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T13:52:51.674+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:52:51.689+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080751, end_date=20240618T080751
[2024-06-18T13:52:51.715+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:52:51.740+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:52:51.745+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
