[2024-06-18T13:55:03.801+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:55:03.820+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:00:00+00:00 [queued]>
[2024-06-18T13:55:03.826+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:00:00+00:00 [queued]>
[2024-06-18T13:55:03.827+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:55:03.850+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:00:00+00:00
[2024-06-18T13:55:03.853+0545] {standard_task_runner.py:63} INFO - Started process 17940 to run task
[2024-06-18T13:55:03.859+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp68oq68bh']
[2024-06-18T13:55:03.860+0545] {standard_task_runner.py:91} INFO - Job 5: Subtask backup_task
[2024-06-18T13:55:03.920+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:00:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:55:04.008+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T08:00:00+00:00'
[2024-06-18T13:55:04.009+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:55:04.011+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T13:55:04.012+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T13:55:04.020+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T13:55:04.028+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:55:04.060+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T13:55:04.070+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T13:55:04.094+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T13:55:04.094+0545] {subprocess.py:93} INFO - Backup Success in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1257.88GB
[2024-06-18T13:55:04.095+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T13:55:04.096+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:55:04.119+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:00:00+00:00, execution_date=20240618T080000, start_date=20240618T081003, end_date=20240618T081004
[2024-06-18T13:55:04.152+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:55:04.190+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:55:04.197+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
